### ISSUE TITLE
Does not work with lumen 5.2 due to version check

### ISSUE THREAD

**Issue by beerbuddha** [mailerlite/laravel-elasticsearch#10]
in your LumenServiceProvider you do a version check but in Lumen, that constant has been removed:
https://github.com/laravel/lumen-framework/blob/master/src/Application.php

Even on the bleeding edge version (5.3.x) it won't be back.

Currently the proposed "hack" is to make a new container and extend this to include the const. Ideally, it should be fixed in your package since that is no longer a valid constant to rely on.

**Comment by cviebrock** [comment]
I'll be honest ... I haven't really used Lumen that much, and not at all with this package.  😜 

Looking at the code, I feel like the `if {...}` wrapper for https://github.com/cviebrock/laravel-elasticsearch/blob/master/src/LumenServiceProvider.php#L29-L35 could be removed.  Those lines to publish the config will need to be run all the time, no?

If you've got time to make a working MR for Lumen, it'd be super appreciated!

**Comment by beerbuddha** [comment]
@cviebrock 
I got your package working in Lumen efficiently. Required a few hacks that i dont like though. So I will try one day (after my project is finished) to submit a PR and insert a few new tests.

Will let you know.

Just hoping that someone will read this thread and use Lumen and will be advised that they will need to "hack" lumen in order to use this package. However you currently have the only good ES package available =)

**Comment by cviebrock** [comment]
#12 should have fixed this ... can you check?
