### ISSUE TITLE
PHPStorm Undefined class 'Elasticsearch'

### ISSUE THREAD

**Issue by chelkaz** [mailerlite/laravel-elasticsearch#103]
Works but doesn't highlight the class
use Elasticsearch;
Elasticsearch::indices()->delete(['index' => '*']);
 "Undefined class 'Elasticsearch'"

**Comment by cviebrock** [comment]
Did #88 fix this for you?  You didn't indicate which version you are using.

**Comment by cviebrock** [comment]
Closing due to no response.  Feel free to re-open or comment if you are still having issues.
