### ISSUE TITLE
does not support php 8

### ISSUE THREAD

**Issue by vikas-agent** [mailerlite/laravel-elasticsearch#107]
updated my composer.json file to 

```
 "require": {
        "php": "^7.2||^8.0",
}
```
but when I do composer update. I'm getting the below error in the command line

```
❯ composer update
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - cviebrock/laravel-elasticsearch[4.2.0, ..., 4.x-dev] require php ^7.2.5 -> your php version (8.0.0) does not satisfy that requirement.
    - Root composer.json requires cviebrock/laravel-elasticsearch ^4.2 -> satisfiable by cviebrock/laravel-elasticsearch[4.2.0, 4.2.1, 4.2.2, 4.x-dev].
```
Can you have a look at this issue a I really want to update my PHP version to PHP 8.

**Comment by cviebrock** [comment]
It looks like the official ES client doesn't support PHP 8.0 yet (see https://github.com/elastic/elasticsearch-php/issues/1084 and https://github.com/elastic/elasticsearch-php/pull/1063).

When the official client adds support, I will update this package!

**Comment by david-kristin** [comment]
It looks like the PHP 8 is [already supported](https://github.com/elastic/elasticsearch-php/pull/1063).

**Comment by david-kristin** [comment]
It looks like the client is [already supporting](https://github.com/elastic/elasticsearch-php/issues/1084#issuecomment-747061052) PHP 8.0.

**Comment by cviebrock** [comment]
It will be supported in their 7.11.0 release, but currently that's still unreleased.  Version 7.10.0 does not yet support PHP 8:

https://github.com/elastic/elasticsearch-php/blob/v7.10.0/composer.json

**Comment by linslin** [comment]
It was released: https://github.com/elastic/elasticsearch-php/blob/7.11/composer.json

`  "require": {
    "php": "^7.1 || ^8.0",
    "ext-json": ">=1.3.7",
    "ezimuel/ringphp": "^1.1.2",
    "psr/log": "~1.0"
  },`

**Comment by cviebrock** [comment]
@linslin I don't think so.  You're looking at a `7.11` branch.  I don't see a 7.11 on their [releases page](https://github.com/elastic/elasticsearch-php/releases).

**Comment by webcreation-sk** [comment]
@cviebrock 
https://github.com/elastic/elasticsearch-php/issues/1083#issuecomment-777387605

7.11 is released and support PHP 8
