### ISSUE TITLE
error while installing cviebrock/laravel-elasticsearch on laravel 7

### ISSUE THREAD

**Issue by swapnilphadke02** [mailerlite/laravel-elasticsearch#113]
I am using PHP 7.3 and Elasticsearch 7 on my local machine.

while installing Elasticsearch i am getting the following error.

Using version ^8.0 for cviebrock/laravel-elasticsearch
./composer.json has been updated
Running composer update cviebrock/laravel-elasticsearch
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - cviebrock/laravel-elasticsearch[8.0.0, ..., 8.0.1] require illuminate/support ^8.0 -> found illuminate/support[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - cviebrock/laravel-elasticsearch[8.0.2, ..., 8.0.3] require illuminate/contracts ^8.0 -> found illuminate/contracts[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires cviebrock/laravel-elasticsearch ^8.0 -> satisfiable by cviebrock/laravel-elasticsearch[8.0.0, 8.0.1, 8.0.2, 8.0.3].

**Comment by cviebrock** [comment]
The 8.x versions of this package are for Laravel 8.0 only, so I'm going to guess that maybe you are using an earlier version?

Either try installing the package without specifying any version to let Composer figure it out:

```sh
composer require cviebrock/laravel-elasticsearch
```

Or, if you must specify, then version 4.2.2 should work.
