### ISSUE TITLE
please show how i can return with paginate

### ISSUE THREAD

**Issue by vahidalvandi** [mailerlite/laravel-elasticsearch#114]
Please be sure you include all the relevant information in your issue so we can help you:

- [ ] steps taken to reproduce your issue
- [ ] your configuration file(s), where relevant
- [ ] a copy of your Models that use or extend this package (just the relevant parts!)
- [ ] any other code we might need to help

Please use a descriptive title for your issue.  "Why doesn't this work?" doesn't provide 
other users much information if they are scanning the list of issues.

Also, *please* use [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/)
when pasting more than one line of code.  It makes it so much more readable for everyone!

**Thank you!**

**Comment by cviebrock** [comment]
Please refer to the [official client documentation](https://github.com/elastic/elasticsearch-php) for information on how to use the ElasticSearch client.  This package is simply a helper to configure the official client in a more Laravel-friendly way and doesn't provide any functionality apart from setting up the configuration.
