### ISSUE TITLE
composer require cviebrock/laravel-elasticsearch

### ISSUE THREAD

**Issue by mliuchengyu** [mailerlite/laravel-elasticsearch#116]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires illuminate/support 8.23.1, found illuminate/support[v8.23.1] but it conflicts with another require.
  Problem 2
    - cviebrock/laravel-elasticsearch[8.0.0, ..., 8.0.1] require illuminate/support ^8.0 -> found illuminate/support[v8.0.0, ..., 8.x-dev] but it conflicts with another require.
    - cviebrock/laravel-elasticsearch[8.0.2, ..., 8.0.3] require illuminate/contracts ^8.0 -> found illuminate/contracts[v8.0.0, ..., 8.x-dev] but it conflicts with another require.
    - Root composer.json requires cviebrock/laravel-elasticsearch ^8.0 -> satisfiable by cviebrock/laravel-elasticsearch[8.0.0, 8.0.1, 8.0.2, 8.0.3].

**Comment by cviebrock** [comment]
Which version of Laravel are you using, 8.23?

I just tried this with a fresh project and had no issues:

```sh
composer create-project laravel/laravel laravel8
cd laravel8
composer require cviebrock/laravel-elasticsearch
```

Can you post your entire composer.json file?

**Comment by mliuchengyu** [comment]
laravel/framework 7.24

composer file

http://nkcjs.oss-cn-qingdao.aliyuncs.com/composer.json

**Comment by cviebrock** [comment]
I think you'll want the 4.2.2 version of the package then.

**Comment by mliuchengyu** [comment]
It worked. Thank you
