### ISSUE TITLE
Installation error on laravel 5.8.*

### ISSUE THREAD

**Issue by giovannidalmas1967** [mailerlite/laravel-elasticsearch#117]
I have run this comand:

composer require cviebrock/laravel-elasticsearch

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install cviebrock/laravel-elasticsearch 4.2.1 (conflict analysis result)
    - Conclusion: don't install cviebrock/laravel-elasticsearch 4.2.2 (conflict analysis result)
    - Root composer.json requires cviebrock/laravel-elasticsearch ^4.2 -> satisfiable by cviebrock/laravel-elasticsearch[4.2.0, 4.2.1, 4.2.2].
    - Conclusion: don't install laravel/framework v5.8.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.4 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.5 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.6 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.7 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.8 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.9 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.10 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.11 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.12 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.13 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.14 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.15 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.16 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.17 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.18 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.19 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.20 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.21 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.22 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.23 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.24 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.25 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.26 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.27 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.28 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.29 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.30 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.31 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.32 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.33 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.34 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.35 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.36 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.37 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.38 (conflict analysis result)
    - Conclusion: don't install laravel/framework v5.8.1 (conflict analysis result)
    - cviebrock/laravel-elasticsearch 4.2.0 requires illuminate/contracts ^6.0|^7.0 -> satisfiable by illuminate/contracts[v6.0.0, ..., v6.20.13, v7.0.0, ..., v7.30.3].
    - Only one of these can be installed: illuminate/contracts[v5.0.0, ..., v5.8.36, v6.0.0, ..., v6.20.13, v7.0.0, ..., v7.30.3, v8.0.0, ..., v8.23.1], laravel/framework[v5.8.0, ..., v5.8.38]. laravel/framework replaces illuminate/contracts and thus cannot coexist with it.
    - Root composer.json requires laravel/framework 5.8.* -> satisfiable by laravel/framework[v5.8.0, ..., v5.8.38].

Installation failed, reverting ./composer.json to its original content.

Thanks in advance

**Comment by giovannidalmas1967** [comment]
This is my composer.json:

{
  "name": "laravel/laravel",
  "description": "The Laravel Framework.",
  "keywords": [
    "framework",
    "laravel"
  ],
  "license": "MIT",
  "type": "project",
  "require": {
    "php": ">=7.2",
    "ext-dom": "*",
    "ext-json": "*",
    "ext-libxml": "*",
    "ext-simplexml": "*",
    "ext-zip": "*",
    "doctrine/dbal": "^2.9",
    "fideloper/proxy": "^4.0",
    "laravel/cashier": "~9.0",
    "laravel/framework": "5.8.*",
    "laravel/nexmo-notification-channel": "^2.0",
    "laravel/slack-notification-channel": "^2.0",
    "laravel/spark-aurelius": "*@dev",
    "laravel/tinker": "~1.0",
    "mpociot/vat-calculator": "^2.4",
    "webpatser/laravel-uuid": "^3.0"
  },
  "require-dev": {
    "barryvdh/laravel-debugbar": "^3.1",
    "barryvdh/laravel-ide-helper": "^2.6",
    "beyondcode/laravel-dump-server": "^1.0",
    "filp/whoops": "~2.0",
    "fzaninotto/faker": "~1.4",
    "mockery/mockery": "^1.0",
    "nunomaduro/collision": "^3.0",
    "phpunit/phpunit": "~8.0"
  },
  "autoload": {
    "classmap": [
      "database/seeds",
      "database/factories"
    ],
    "psr-4": {
      "App\\": "app/"
    },
    "files": [
      "app/helpers.php"
    ]
  },
  "autoload-dev": {
    "psr-4": {
      "Tests\\": "tests/"
    }
  },
  "extra": {
    "laravel": {
      "dont-discover": []
    }
  },
  "scripts": {
    "post-root-package-install": [
      "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
    ],
    "post-create-project-cmd": [
      "@php artisan key:generate"
    ],
    "post-autoload-dump": [
      "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
      "@php artisan package:discover"
    ]
  },
  "config": {
    "preferred-install": "dist",
    "sort-packages": true,
    "optimize-autoloader": true
  },
  "repositories": [
    {
      "type": "path",
      "url": "./spark"
    }
  ]
}

**Comment by cviebrock** [comment]
Try version 4.1.3 of the package.  That was the last version meant to be used with Laravel 5.8.

**Comment by giovannidalmas1967** [comment]
I will try it. Let you know. Thanks a lot

**Comment by giovannidalmas1967** [comment]
It worked, thanks a lot!

**Comment by giovannidalmas1967** [comment]
I tried to do some tests and tried to run "php artisan laravel-elasticsearch:...", the result is that the command "laravel-elasticsearch" is not defined. Have I missed something on package's installation and configuration? 

Thanks in advance

**Comment by cviebrock** [comment]
Closing old tickets.  There is no artisan command by that name in the package.
