### ISSUE TITLE
Laravel 8 w/ ES 5

### ISSUE THREAD

**Issue by xLink** [mailerlite/laravel-elasticsearch#120]
Is there any chance of an upgrade to the version that works with ES5 so it can work with Laravel 8? An upgrade to my ES server is in the works but its not a small under taking. 

Thanks in advance

**Comment by xLink** [comment]
So after doing some testing on my end, looks like the package from 4.1 branch works if given the ^7|^8 version upgrades to laravel.

**Comment by cviebrock** [comment]
Closing old tickets.
