### ISSUE TITLE
Can't cache configuration when using logObject

### ISSUE THREAD

**Issue by apokryfos** [mailerlite/laravel-elasticsearch#121]
I am trying to cache my configuration while also using the default laravel logger in Laravel 8

- steps taken to reproduce the issue
  1. created new laravel project using `laravel new estest`
  2. Tried setting the `logObject` configuration setting to the documented `\Log::getMonolog()` but that does not work (I think that's outdated). I have also tried using `'logObject' => (new \Illuminate\Log\LogManager(app()))->driver()->getLogger()`.  however when running `php artisan config:cache`  I get an error `Your configuration files are not serializable.`
- your configuration file(s), where relevant
```
'logging' => true,
'logObject' => (new \Illuminate\Log\LogManager(app()))->driver()->getLogger(),
```

I would like to just use the same logger I use normally and also cache my configuration. 

Not sure I'm missing something here. Is it meant to be possible to cache the configuration when doing this? Is there an alternative?

**Comment by cviebrock** [comment]
You can't serialize that value.  I believe you would need to make a class with a method that returns that value ... something like:
```php
class Foo
    function getLogObject() {
        return (new \Illuminate\Log\LogManager(app()))->driver()->getLogger();
    }
}
```
and then pass that in your config as a callable:
```php
'logObject' => [Foo:class, 'getLogObject'],
```

**Comment by cviebrock** [comment]
Closing due to no response.  Feel free to re-open or comment if you are still having issues.
