### ISSUE TITLE
Undefined index: host when check exists index

### ISSUE THREAD

**Issue by bigcandy95** [mailerlite/laravel-elasticsearch#123]
I just use package to connect to ES AWS but I got this error( https://tinyurl.com/ydwpddsg). Follow this error may be my config lose something but I don't know

**Comment by rubalGulati2018** [comment]
I am facing same error.

**Comment by cviebrock** [comment]
I see you've blurred out the full value for `$request['headers']['Host'][0]` ... but the error has to do with PHP not being able to parse that value with `parse_url`.

Are you able to provide that value, un-blurred?  Or even just the beginning of it?  Or does that compromise credentials/security on your side?  If so, you can email me the value confidentially (colin at viebrock dot ca).

**Comment by sete391** [comment]
I send a PR to solve it:

https://github.com/cviebrock/laravel-elasticsearch/pull/124
