### ISSUE TITLE
Error: After last composer update

### ISSUE THREAD

**Issue by douglasmiguel** [mailerlite/laravel-elasticsearch#13]
> PHP Fatal error:  Call to undefined method Cviebrock\LaravelElasticsearch\ServiceProvider::publishes() in {project}/vendor/cviebrock/laravel-elasticsearch/src/ServiceProvider.php on line 32
> {"error":{"type":"Symfony\Component\Debug\Exception\FatalErrorException","message":"Call to undefined method Cviebrock\LaravelElasticsearch\ServiceProvider::publishes()","file":"{project}\/vendor\/cviebrock\/laravel-elasticsearch\/src\/ServiceProvider.php","line":32}}Script php artisan clear-compiled handling the post-update-cmd event returned with an error
> 
> [RuntimeException]
> Error Output: PHP Fatal error:  Call to undefined method Cviebrock\LaravelElasticsearch\ServiceProvider::publishes() in {project}/ve
>   ndor/cviebrock/laravel-elasticsearch/src/ServiceProvider.php on line 32

**I solved this by commenting the following code block:**

Line 32:
// $this->publishes([
//     $configPath => config_path('elasticsearch.php'),
// ]);

Apparently the **_ServiceProviderBase_** remove method **_publishes_**.

**Comment by douglasmiguel** [comment]
**Important information:** I am using the 4.2 version of Laravel.

**Comment by cviebrock** [comment]
Ah yeah, the latest version is L5 only now. Sorry.  I should have updated the composer.json file accordingly.
