### ISSUE TITLE
"type":"action_request_validation_exception","reason":"Validation Failed: 1: mapping type is missing;"},"status":400}

### ISSUE THREAD

**Issue by Dasinfomedia2** [mailerlite/laravel-elasticsearch#130]
Please be sure you include all the relevant information in your issue so we can help you:

- create json file for index as per the document
- RUN - php artisan laravel-elasticsearch:utils:index-create articles

Please use a descriptive title for your issue.  "Why doesn't this work?" doesn't provide 
other users much information if they are scanning the list of issues.

Also, *please* use [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/)
when pasting more than one line of code.  It makes it so much more readable for everyone!

**Thank you!**

**Comment by cviebrock** [comment]
It looks like you have a question about how to do something with the Elasticsearch client in your Laravel application, or are having issues connecting to your Elastic instance.

Please refer to the [official documentation](https://github.com/elastic/elasticsearch-php) for information on how to use the Elasticsearch client.  My package is simply a wrapper around the official client that makes it easier to configure your ES connection in a more Laravel-friendly way.  The package doesn't provide any functionality apart from setting up the configuration.
