### ISSUE TITLE
Possiblity to get mappings

### ISSUE THREAD

**Issue by tebulrich** [mailerlite/laravel-elasticsearch#132]
Hi, is it somehow possible to get the mapping definitions? I have an index with lots of documents and i need all the field names.

**Comment by cviebrock** [comment]
It looks like you have a question about how to do something with the Elasticsearch client in your Laravel application, or are having issues connecting to your Elastic instance.

Please refer to the [official documentation](https://github.com/elastic/elasticsearch-php) for information on how to use the Elasticsearch client.  My package is simply a wrapper around the official client that makes it easier to configure your ES connection in a more Laravel-friendly way.  The package doesn't provide any functionality apart from setting up the configuration.
