### ISSUE TITLE
Move from 4.2.2 to 8.x version

### ISSUE THREAD

**Issue by shirokovnv** [mailerlite/laravel-elasticsearch#136]
Hello!

Thanks for the package! 

Is there any link with info about migration from 4.2.2 to 8.x ?

Have not found any information about breaking changes between versions.

Or I can do `composer update` without any risk of class api-s to be broken?

**Comment by cviebrock** [comment]
Slow response ... sorry.

I don't know offhand of what differences there were between 4.2.2 and 8.x (or 9.x).  There is the [Changelog](https://github.com/cviebrock/laravel-elasticsearch/blob/master/CHANGELOG.md), where I try to list all the changes between various versions (and note if anything is a breaking change).

And there is, of course, git history. 😉 

Looks to me like the only things that might be issues are that 9.x:
- only supports Laravel 7, 8 and 9, and PHP 7.3–8.1
- uses `guzzlehttp/psr7` version `^2.0` (if you use it elsewhere in your project)
- uses `elasticsearch/elasticsearch` version `^7.11`

I don't think there are any breaking changes to the format of the configuration files, so you are _probably_ safe to update.

**Comment by shirokovnv** [comment]
Thanks, figured it out.
