### ISSUE TITLE
Upgrade guzzlehttp/psr7

### ISSUE THREAD

**Issue by applyACS** [mailerlite/laravel-elasticsearch#138]
Can the guzzlehttp/psr7 package be upgraded to v2?
I have conflicts with other packages

**Comment by cviebrock** [comment]
Version 9.0.1 of the package has this upgrade.  Let me know if it works for you.

**Comment by brunogaspar** [comment]
@cviebrock Could a range like `^1.7|^2.0` be used instead?

I can PR it if you prefer :)

Thank you!

**Comment by cviebrock** [comment]
@brunogaspar done in 9.0.2.  Thanks for the suggestion ... I should've thought of that myself!

**Comment by brunogaspar** [comment]
All good and thank you very much for the quick action, really appreciate it :)
