### ISSUE TITLE
Package guzzle/guzzle is abandoned

### ISSUE THREAD

**Issue by nicobrinkkemper** [mailerlite/laravel-elasticsearch#14]
Title says it all. Following the guidelines we get:
`Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.`

**Comment by cviebrock** [comment]
Hrm ...  my package isn't requiring `guzzle/guzzle` directly.  And I see that the ES package I do require isn't using it either (I don't think).

Maybe something else is requiring it?  Try `composer show -t` to get a dependency tree and look for it?

**Comment by cviebrock** [comment]
Re-open if you find anything related to this project that needs adjusting.
