### ISSUE TITLE
documentation and/or examples

### ISSUE THREAD

**Issue by theraaz** [mailerlite/laravel-elasticsearch#15]
I've used elasticsearch in Node.JS but never used in PHP/Laravel. Tried to play around but couldn't understand how to do. Is it possible to provide some examples and documentation other than main readme.md file?

**Comment by cviebrock** [comment]
Since this package is basically just a nice wrapper for the office ES PHP client, taking at look at [their documentation](https://github.com/elastic/elasticsearch-php) is probably the best place to start.
