### ISSUE TITLE
NoNodesAvailableException: No alive nodes found in your cluster

### ISSUE THREAD

**Issue by ravenKaisar** [mailerlite/laravel-elasticsearch#152]
<img width="1362" alt="image" src="https://github.com/mailerlite/laravel-elasticsearch/assets/16849877/88e439fc-b69d-4b16-b102-8f751d7f5273">

**Comment by devhaozi** [comment]
Set `sslVerification` to `false` in config/elasticsearch.php works for me.

**Comment by shuvroroy** [comment]
Looks like config related issue.
