### ISSUE TITLE
Any idea what happened to the elasticsearch package?

### ISSUE THREAD

**Issue by apokryfos** [mailerlite/laravel-elasticsearch#157]
I was trying to install this package and got the error

```
Failed to download elasticsearch/elasticsearch from dist: The "https://api.github.com/repos/elastic/elasticsearch-php/zipball/2d302233f2bb0926812d82823bb820d405e130fc" file could not be downloaded (HTTP/2 404 ):
 {"message":"Not Found","documentation_url":"https://docs.github.com/rest/repos/contents#download-a-repository-archive-zip","status":"404"}
  Now trying to download from source
```

I had a look and https://packagist.org/packages/elasticsearch/elasticsearch mentions that it's gone. 

I know this is not technically an issue of this package, but it is causing installing this package to fail installation. I'm just wondering if there's any idea as to what has happened since that seems to be the official elasticsearch php package.

**Comment by islamsamy214** [comment]
the same happend with me!!

**Comment by apokryfos** [comment]
Apparently it was not intentional https://status.elastic.co/incidents/9mmlp98klxm1 and it is now back
