### ISSUE TITLE
Support for 5.x

### ISSUE THREAD

**Issue by Spechal** [mailerlite/laravel-elasticsearch#19]
Can you bump the version support to include elasticsearch 5.x if everything tests out?

**Comment by cviebrock** [comment]
Sorry for the delay.  I don't have a nice environment set up to test this.  If you do, and can confirm it works with ES 5.x, I'd be happy to bump the version.

**Comment by shequet** [comment]
I've tested with the 5th version of elasticsearch and it works perfectly. Could you please update the composer to include this specific version ?
`"elasticsearch/elasticsearch": "^5.0"`

Best regards

**Comment by cviebrock** [comment]
Updated, and bumped this package version to 2.0.0.  Thanks!
