### ISSUE TITLE
Issue with namespace

### ISSUE THREAD

**Issue by ryantology** [mailerlite/laravel-elasticsearch#2]
I think there is an issue with the namespaces of this package. It could be an issue with my application but after install the following error is generated:

```
  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'Cviebrock\LaravelElasticSearch\ElasticServiceProvider' not found
```

Checking the `autoload_classmap.php` the classes look like they exist properly:

```
    'Cviebrock\\LaravelElasticsearch\\ServiceProvider' => $vendorDir . '/cviebrock/laravel-elasticsearch/src/ServiceProvider.php',
    'Cviebrock\\LaravelElasticsearch\\Facade' => $vendorDir . '/cviebrock/laravel-elasticsearch/src/Facade.php',
    'Cviebrock\\LaravelElasticsearch\\Factory' => $vendorDir . '/cviebrock/laravel-elasticsearch/src/Factory.php',
    'Cviebrock\\LaravelElasticsearch\\Manager' => $vendorDir . '/cviebrock/laravel-elasticsearch/src/Manager.php',
```

Looking over the code I did not see any issue with the namespaces that seemed obvious. My app config line looks like this:

```
    'providers' => [
...
    Cviebrock\LaravelElasticSearch\ServiceProvider::class,
```

Will come back to this next week when I have more time and can install on a fresh laravel project.

**Comment by cviebrock** [comment]
I'm not somewhere where I can easily check, but a quick glance I see that the error is "Class 'Cviebrock\LaravelElasticSearch\ **ElasticServiceProvider** ' not found", but the class is actually Cviebrock\LaravelElasticSearch\ **ServiceProvider** .

I'll scan my code and see if I made a typo somewhere, or if the docs are off.

**Comment by cviebrock** [comment]
Okay, quick scan of my code doesn't show "ElasticServiceProvider" anywhere, and it looks like everything uses `namespace Cviebrock\LaravelElasticsearch`.

Maybe double-check your app configuration? Your comment above says you have `Cviebrock\LaravelElasticSearch\ServiceProvider::class` ... I bet that capital S in "Search" is messing things up.

**Comment by ryantology** [comment]
Oh, thats a bad copy and paste from me. I was messing with stuff after it
broke to see if there was a conflict with my app. So I renamed it for a
second and then named it back. The error happens with another developer as
well (that didn't rename the file :) )

The capital S is 99% the cause. I will do another test and send in a PR for
the docs.
