### ISSUE TITLE
References

### ISSUE THREAD

**Issue by cjsjtec** [mailerlite/laravel-elasticsearch#21]
Implements references: https://github.com/elastic/elasticsearch-php

**Comment by cviebrock** [comment]
I'm not sure what you are asking.

**Comment by cjsjtec** [comment]
Includes a reference for elasticsearch-php

**Comment by cviebrock** [comment]
I'm sorry, I still don't know what the issue is.  Are you asking that I reference that ... somewhere? Or ...?

**Comment by cjsjtec** [comment]
Inserts a reference to the elasticsearch-php documentation in README.md
