### ISSUE TITLE
FatalThrowableError: Class 'App\Http\Controllers\Elasticsearch' not found

### ISSUE THREAD

**Issue by ralphreijs** [mailerlite/laravel-elasticsearch#24]
Hi,

I followed the instructions on installation and usage in the ReadMe 3 times, every time starting over with a fresh Laravel project and removing composer packages that were left behind because of global installs. Somehow I keep getting the same error, regardless of the fresh installs.

I'm really new to Laravel, but so far things seem to make sense and I have been able to solve my issues with logic and reasoning an googling.  But this issue keeps returning and I can't figure out why this is happening. Can someone tell me why this is happening, and what I'm doing wrong?

I'm using Laravel Framework 5.4.24 and ElasticSearch 5.2.2.

Thanks!

canphaz

<img width="858" alt="screen shot 2017-06-04 at 20 23 18" src="https://cloud.githubusercontent.com/assets/203897/26764240/b9fbeb14-4963-11e7-97c3-21c6d543370e.png">
<img width="645" alt="screen shot 2017-06-04 at 20 17 33" src="https://cloud.githubusercontent.com/assets/203897/26764241/ba1d6c44-4963-11e7-925e-07786d25fc4b.png">

**Comment by Mechtecs** [comment]
You forgot use Elasticsearch; as an import at the top of the file ;)

**Comment by ralphreijs** [comment]
@Mechtecs Thanks for your help man! 

I tried that as well, but getting the same message.. that's where it stops making sense to me :-) I'm not very experienced with namespacing and importing libraries, but I tried the following and none of them work, even with completely clean projects:

use App\ElasticSearch\ElasticSearch;
use App\elasticsearch\elasticsearch;
use App\Elasticsearch\Elasticsearch;
use ElasticSearch\ElasticSearch;
use elasticsearch\elasticsearch;
use Elasticsearch\Elasticsearch;

But regardless which one I try, I get the same error. Could you give me an example how to import it correctly? Or perhaps I somehow messed up the composer packages? How can I check this, there are no errors when I use compose to require the necessary packages, and `composer info` shows following output (see attached screenshot)
<img width="1094" alt="screen shot 2017-06-05 at 10 50 16" src="https://cloud.githubusercontent.com/assets/203897/26777368/35d3a5dc-49dd-11e7-864f-b83f72c09954.png">

**Comment by cviebrock** [comment]
You shouldn't import anything at the top of your file with `use **/ElasticSearch`.

Assuming you have the entry in the `facades` array in `config.app.php` you can just use:

```php
$return = \Elasticsearch::index($data);
```

Your original error was because you have a namespace on your controller (`App\Http\Controllers`) and you didn't prefix the ES class with a `\` ... so PHP assumes it's in the same namespace (`App\Http\Controllers\Elasticsearch`).

Prefixing it with a slash means use the class with no namespace, in which case Laravel's facade system kicks in.

If you are dead-set against facades, you can use:

```php
app('elasticsearch')->index($data);
```

Or inject the ES client into your controller (this package's service provider will take care of the details):

```php
public function constructor(\Elasticsearch\Client $elastic) {
    $this->elastic = $elastic;
}

public function index() {
    // ...
    $this->elastic->index($data);
    // ...
}
```

**Comment by ralphreijs** [comment]
Thank you for the thorough reply and explanation @cviebrock ! :-)

**Comment by sonalmhatre** [comment]
hello,
I have also same error,IS this working your project of adding above code??
i am also using above code but stilled its not working!!
Please help me for solving this issue
