### ISSUE TITLE
php artisan vendor:publish --provider="Cviebrock\LaravelElasticsearch\ServiceProvider"

### ISSUE THREAD

**Issue by bekee** [mailerlite/laravel-elasticsearch#30]
elastic config file is not published

**Comment by rsantos** [comment]
same problem

**Comment by marcusmoore** [comment]
Are you using Laravel or Lumen? What version?

**Comment by gozhhu** [comment]
>> Nothing to publish for tag [].

**Comment by rsantos** [comment]
Hi @marcusmoore.
I was using laravel 5.4, I updated to laravel 5.5 and it worked.

**Comment by marcusmoore** [comment]
Interesting. I just installed it in an 5.4 app just fine. 
I wonder if, during the update from 5.4 to 5.5, you updated this package's version to `2.0.1` which added the `extra` auto-publishing bit and that changed something.

**Comment by cviebrock** [comment]
Going to close this since it all seems sorted out now.

**Comment by andrewblaney** [comment]
If I try to install on 5.3, nothing is published. I also get the message:

```Nothing to publish for tag [].```

Laravel: `5.3.31`
Composer: `"cviebrock/laravel-elasticsearch": "^2"`

**Comment by cviebrock** [comment]
Laravel 5.3 didn't support auto-registering packages and aliases.  You will need to add:

```
Cviebrock\LaravelElasticsearch\ServiceProvider::class
```

 to your list of providers and:

```
'Elasticsearch' => Cviebrock\LaravelElasticsearch\Facade::class
```
to the aliases array, both in `config/app.php`.

(Keep in mind that Github shows the README for the master branch.  You should always look at the version specific to your release.  In this case, https://github.com/cviebrock/laravel-elasticsearch/tree/2.0 has the right info for you.)

**Comment by habib-jalal** [comment]
Sir i am getting this error...
In ProviderRepository.php line 208:
  Class 'Cviebrock\LaravelElasticSearch\ServiceProvider' not found
--------------------------
here is my line 208
public function createProvider($provider)
    {
        return new $provider($this->app);
    }
