### ISSUE TITLE
InvalidArgumentException Elasticsearch connection [] not configured.

### ISSUE THREAD

**Issue by KinnaT** [mailerlite/laravel-elasticsearch#35]
Hello,
I tried looking through the docs, closed issues and every config permutation I could think of and still can't resolve this error.

Using package v2.0.0, Laravel 5.5.23, Elasticsearch 6.0.0
The error is being thrown by \vendor\cviebrock\laravel-elasticsearch\src\Manager.php line 108.

.env has the following variables set:
```
ELASTICSEARCH_HOST
ELASTICSEARCH_PORT
ELASTICSEARCH_SCHEME
ELASTICSEARCH_USER
ELASTICSEARCH_PASS
```

config\app.php has:
```
'providers' => [
. . .
/* Package list */
Cviebrock\LaravelElasticsearch\ServiceProvider::class
],
'aliases' => [
. . .
'Elasticsearch' => Cviebrock\LaravelElasticsearch\Facade::class,
],
```
ElasticController.php is:
```
<?php

namespace App\Http\Controllers;

use App\Dashboard;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class ElasticController extends Controller {

	public function index(Request $request) {
		$return = \Elasticsearch::ping();

		return view('welcome', compact('return'));
	}
}
```

**Comment by cviebrock** [comment]
You probably want to bump the package version to ^3 if you are using ES 6, although that wouldn't explain the error.

Did you publish the configuration file `config/elasticsearch.php` with this:

```sh
php artisan vendor:publish --provider="Cviebrock\LaravelElasticsearch\ServiceProvider"
```

**Comment by KinnaT** [comment]
I had published it and it was present when opening the issue.
I wasn't aware there was a v3. I would recommend that the installation doc be updated to reflect this.
Updating to 3.0 (which requires updating elasticsearch to 6.0 in composer.json as well) resolved this.

Thanks!

**Comment by petercoles** [comment]
Installation per the readme will automatically pull in v3. There's no need to include any version of Elasticsearch in your composer.json, and it's best not to, as this package takes care of that.

**Comment by KinnaT** [comment]
Thanks for the tip! Removed ES from composer.json for futureproofing.
