### ISSUE TITLE
Elasticsearch working with multiple tables??

### ISSUE THREAD

**Issue by ryanslcdevshop** [mailerlite/laravel-elasticsearch#38]
Can i use elasticsearch with multiple tables using laravel relationships?? 

**Thank you!**

**Comment by cviebrock** [comment]
My package doesn't work as a replacement database driver for Eloquent, which is what I _think_ you are looking for.  This package just makes it easy to instantiate and configure the official ES client class.

It may be a bit out-of-date, but something like [Elasticquent](https://github.com/elasticquent/Elasticquent) might be what you need?

**Comment by cviebrock** [comment]
Closing due to no response.  Feel free to re-open or comment if you are still having issues.
