### ISSUE TITLE
Can't upgrade Laravel to 5.6

### ISSUE THREAD

**Issue by ahmadazimi** [mailerlite/laravel-elasticsearch#39]
Recently I'm going to upgrade my Laravel version to the latest 5.6.3.
But the following issue in the laravel-elasticsearch stop it!

![image](https://user-images.githubusercontent.com/1847191/36322763-c40c6064-1363-11e8-97e5-a0993bea5bc6.png)

**Comment by cviebrock** [comment]
New job ... haven't had time to upgrade the package to work with 5.6 yet.  I think there is a PR for it, so I'll do that shortly.

**Comment by cviebrock** [comment]
Upgrade to 3.1.1 of the package, and you should be good!

**Comment by ahmadazimi** [comment]
@cviebrock Thank you.
It works fine
