### ISSUE TITLE
Class path.config does not exist

### ISSUE THREAD

**Issue by JatinSethi** [mailerlite/laravel-elasticsearch#41]
On Lumen: 5.4

When I followed the documentation and tried to run tinker, I got below:

    [ReflectionException]
        Class path.config does not exist

I resolved this issue by replacing:

    $app->register(Cviebrock\LaravelElasticsearch\ServiceProvider::class);

with:

    $app->register(Cviebrock\LaravelElasticsearch\LumenServiceProvider::class);

I think the documentation has this incorrect. Maybe you copied the line from the Laravel section and forgot to rename the `ServiceProvider::class` with `LumenServiceProvider::class`

**Comment by cviebrock** [comment]
I think you must have an older version of the package, but are reading the documentation for a later version.

The latest version of the package only has one ServiceProvider that can work with both Laravel and Lumen.  If you still have a LumenServiceProvider, then you are on a 2.* release of the package, in which case the [docs for that version](https://github.com/cviebrock/laravel-elasticsearch/blob/2.0.1/README.md) are correct.
