### ISSUE TITLE
Not able to access on AWS Elastic search cluster

### ISSUE THREAD

**Issue by abhibaranwal** [mailerlite/laravel-elasticsearch#43]
Hi , 
I have used the package and it works well if I directly use on local server, but when I used the AWS elastic search and changed to below configuration it stoped working

ELASTICSEARCH_HOST=elastic_search_end_point (initially localhost)
ELASTICSEARCH_PORT=80 (initially 9200)
ELASTICSEARCH_SCHEME=http
ELASTICSEARCH_USER=
ELASTICSEARCH_PASS=

**I get below error:**

{"message":"Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header. Authorization=Basic Og=="}

**Elastic Search Aws Services** : https://aws.amazon.com/elasticsearch-service/

Please help me to make this workable , thanks in advance

**Comment by petercoles** [comment]
I'm not using AWS Elasticsearch at the moment so can't test it out, but I vaguely remember that it used to require, rather idiosyncratically, that the scheme be https and the port 443.

Hope that helps.

**Comment by timersys** [comment]
I just installed this on laravel 5.5 and I was getting the error of no nodes available in cluster. I had to change my config file to this to make it work:

` 'hosts' => [
            	'https://'.env('ELASTICSEARCH_USER', null).':'.env('ELASTICSEARCH_PASS', null).'@xxxxx.us-east-1.aws.found.io:9243'
               ];`

I'm not sure if this it's because an update on the original elasticsearch php library, but I tried simplified way as explained in https://www.elastic.co/guide/en/elasticsearch/client/php-api/5.0/_security.html and it wordked for me

**Comment by sfdsfdsfdesfdsghefasefs** [comment]
I want to help related elasticsearch.
how to search in mysql database using elasticseach?

**Comment by npbtrac** [comment]
> I'm not using AWS Elasticsearch at the moment so can't test it out, but I vaguely remember that it used to require, rather idiosyncratically, that the scheme be https and the port 443.
> 
> Hope that helps.

I know it's now 2020 but you just saved me a bunch of time. I use Elasticsearch SDK and the instance on AWS, previously, I put 'https://<aws-service-url.amazonaws.com>' and it didn't work. I tried to debug all the way in the SDK but found nothing. I found your answer and I changed it to 'https://<aws-service-url.amazonaws.com>:443' and it worked. Thanks again!

**Comment by dguzman1012** [comment]
> > I'm not using AWS Elasticsearch at the moment so can't test it out, but I vaguely remember that it used to require, rather idiosyncratically, that the scheme be https and the port 443.
> > Hope that helps.
> 
> I know it's now 2020 but you just saved me a bunch of time. I use Elasticsearch SDK and the instance on AWS, previously, I put 'https://<aws-service-url.amazonaws.com>' and it didn't work. I tried to debug all the way in the SDK but found nothing. I found your answer and I changed it to 'https://<aws-service-url.amazonaws.com>:443' and it worked. Thanks again!

Hey!!! I am wondering.. Where did you setup the host? 'https://<aws-service-url.amazonaws.com>:443' ??? I am facing this issue right now and I'm not sure how to fix it! Thanks!

**Comment by markronquillo** [comment]
> > > I'm not using AWS Elasticsearch at the moment so can't test it out, but I vaguely remember that it used to require, rather idiosyncratically, that the scheme be https and the port 443.
> > > Hope that helps.
> > 
> > 
> > I know it's now 2020 but you just saved me a bunch of time. I use Elasticsearch SDK and the instance on AWS, previously, I put 'https://<aws-service-url.amazonaws.com>' and it didn't work. I tried to debug all the way in the SDK but found nothing. I found your answer and I changed it to 'https://<aws-service-url.amazonaws.com>:443' and it worked. Thanks again!
> 
> Hey!!! I am wondering.. Where did you setup the host? 'https://<aws-service-url.amazonaws.com>:443' ??? I am facing this issue right now and I'm not sure how to fix it! Thanks!

You can define both the host and port in the environment variables
