### ISSUE TITLE
elasticsearch server not connected,getting error No alive nodes found in your cluster

### ISSUE THREAD

**Issue by vikramsinghprajapat** [mailerlite/laravel-elasticsearch#48]
Please be sure you inc
- [ ] steps taken to reproduce your issue
- [ ] your configuration file(s), where relevant
- [ ] a copy of your Models that use or extend this package (just the relevant parts!)
- [ ] any other code we might need to help

Please use a descriptive title for your issue.  "Why doesn't this work?" doesn't provide 
other users much information if they are scanning the list of issues.

Also, *please* use [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/)
when pasting more than one line of code.  It makes it so much more readable for everyone!

**Thank you!**

**Comment by Sauraj1234** [comment]
Not able config the with elasticseach ..could any one please help me.. getting same error (No alive nodes founds in your cluster)
