### ISSUE TITLE
No alive nodes found in your cluster

### ISSUE THREAD

**Issue by vikramsinghprajapat** [mailerlite/laravel-elasticsearch#49]
"message": "No alive nodes found in your cluster",
    "exception": "Elasticsearch\\Common\\Exceptions\\NoNodesAvailableException",
    "file": "C:\\xampp\\htdocs\\erp\\vendor\\elasticsearch\\elasticsearch\\src\\Elasticsearch\\ConnectionPool\\StaticNoPingConnectionPool.php",
    "line": 51,
    "trace": [
        {
            "file": "C:\\xampp\\htdocs\\erp\\vendor\\elasticsearch\\elasticsearch\\src\\Elasticsearch\\Transport.php",
            "line": 72,
            "function": "nextConnection",
            "class": "Elasticsearch\\ConnectionPool\\StaticNoPingConnectionPool",
            "type": "->"
        },

**Comment by saqueib** [comment]
make sure to add `port number` on your elastic search host.

```
...es.amazonaws.com:443
```

**Comment by cviebrock** [comment]
This is almost certainly not an issue with this package, so I'm closing the issue.

**Comment by nickolasnikolic** [comment]
I have the same issue:

nn@nick:~/dev/wd/word.dance$ php artisan elastic:update-mapping "App\User" -v

   Elasticsearch\Common\Exceptions\NoNodesAvailableException  : No alive nodes found in your cluster

  at /home/nn/dev/wd/word.dance/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php:50
    46|                 return $connection;
    47|             }
    48|         }
    49| 
  > 50|         throw new NoNodesAvailableException("No alive nodes found in your cluster");
    51|     }
    52| 
    53|     public function scheduleCheck(): void
    54|     {

  Exception trace:

  1   Elasticsearch\ConnectionPool\StaticNoPingConnectionPool::nextConnection()
      /home/nn/dev/wd/word.dance/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php:77

  2   Elasticsearch\Transport::getConnection()
      /home/nn/dev/wd/word.dance/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php:94

  3   Elasticsearch\Transport::performRequest("PUT", "//word_dance_write/_mapping/users?include_type_name=true", [], "{"users":{"properties":{"name":{"type":"text","fields":{"raw":{"type":"keyword"}}},"bio":{"type":"text","fields":{"raw":{"type":"keyword"}}}}}}", [])
      /home/nn/dev/wd/word.dance/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:269

  4   Elasticsearch\Connections\Connection::Elasticsearch\Connections\{closure}()
      /home/nn/dev/wd/word.dance/vendor/react/promise/src/FulfilledPromise.php:25

  5   React\Promise\FulfilledPromise::then(Object(Closure))
      /home/nn/dev/wd/word.dance/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php:55

  6   GuzzleHttp\Ring\Future\CompletedFutureValue::then(Object(Closure))
      /home/nn/dev/wd/word.dance/vendor/guzzlehttp/ringphp/src/Core.php:341

  7   GuzzleHttp\Ring\Core::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
      /home/nn/dev/wd/word.dance/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:310

  8   Elasticsearch\Connections\Connection::Elasticsearch\Connections\{closure}(Object(Elasticsearch\Connections\Connection), Object(Elasticsearch\Transport), [])
      /home/nn/dev/wd/word.dance/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:211

  9   Elasticsearch\Connections\Connection::performRequest("PUT", "/word_dance_write/_mapping/users", ["true"], "{"users":{"properties":{"name":{"type":"text","fields":{"raw":{"type":"keyword"}}},"bio":{"type":"text","fields":{"raw":{"type":"keyword"}}}}}}", [], Object(Elasticsearch\Transport))
      /home/nn/dev/wd/word.dance/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php:110

  10  Elasticsearch\Transport::performRequest("PUT", "/word_dance_write/_mapping/users", ["true"], [], [])
      /home/nn/dev/wd/word.dance/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/AbstractNamespace.php:58

  11  Elasticsearch\Namespaces\AbstractNamespace::performRequest(Object(Elasticsearch\Endpoints\Indices\Mapping\Put))
      /home/nn/dev/wd/word.dance/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/IndicesNamespace.php:636

  12  Elasticsearch\Namespaces\IndicesNamespace::putMapping(["true"])
      /home/nn/dev/wd/word.dance/vendor/babenkoivan/scout-elasticsearch-driver/src/Console/ElasticUpdateMappingCommand.php:57

  13  ScoutElastic\Console\ElasticUpdateMappingCommand::handle()
      /home/nn/dev/wd/word.dance/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32

  14  call_user_func_array([])
      /home/nn/dev/wd/word.dance/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32

  15  Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
      /home/nn/dev/wd/word.dance/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:90

  16  Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Object(Closure))
      /home/nn/dev/wd/word.dance/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:34

  17  Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), [])
      /home/nn/dev/wd/word.dance/vendor/laravel/framework/src/Illuminate/Container/Container.php:576

  18  Illuminate\Container\Container::call()
      /home/nn/dev/wd/word.dance/vendor/laravel/framework/src/Illuminate/Console/Command.php:183

  19  Illuminate\Console\Command::execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      /home/nn/dev/wd/word.dance/vendor/symfony/console/Command/Command.php:255

  20  Symfony\Component\Console\Command\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      /home/nn/dev/wd/word.dance/vendor/laravel/framework/src/Illuminate/Console/Command.php:170

  21  Illuminate\Console\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /home/nn/dev/wd/word.dance/vendor/symfony/console/Application.php:921

  22  Symfony\Component\Console\Application::doRunCommand(Object(ScoutElastic\Console\ElasticUpdateMappingCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /home/nn/dev/wd/word.dance/vendor/symfony/console/Application.php:273

  23  Symfony\Component\Console\Application::doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /home/nn/dev/wd/word.dance/vendor/symfony/console/Application.php:149

  24  Symfony\Component\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /home/nn/dev/wd/word.dance/vendor/laravel/framework/src/Illuminate/Console/Application.php:90

  25  Illuminate\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /home/nn/dev/wd/word.dance/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:133

  26  Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /home/nn/dev/wd/word.dance/artisan:37

**Comment by petercoles** [comment]
As @cviebrock observed when this was originally raised, this isn't a problem with the package. The clue is in the Exception being thrown: ```Elasticsearch\Common\Exceptions\NoNodesAvailableException : No alive nodes found in your cluster``` which suggests that you have configured the package properly, but when it tries to access your Elasticsearch cluster, it find that you don't have any nodes running.
