### ISSUE TITLE
laravel-elasticsearch v2 - "explain", "from", "highlight", "query", "size" are not valid parameters

### ISSUE THREAD

**Issue by annethereshewent** [mailerlite/laravel-elasticsearch#54]
So we currently are using ElasticSearch version 5.5 on the backend, and I'm trying to use this laravel-elasticsearch client (version ^2) to do queries. however, it complains that several parameters are not valid. These same parameters work when doing a vanilla curl call to the elastic search server, so I'm not sure why they wouldn't work with this client, given that version 2 is supposed to be compatible with Elasticsearch 5. Here is my search query for reference:

        $fields = ['feed_name^2', 'title^2', 'description'];

        $query = [
            'from'      => 0,
            'size'      => 15,
            'explain'   => false,
            'query'     => [
                'function_score' => [
                    'query' => [
                        'bool' => [
                            'must'   => [
                                'multi_match' => [
                                    'query'  => $input['q'],
                                    'type'   => 'cross_fields',
                                    'slop'   => 10,
                                    'fields' => $fields,
                                ]
                            ],
                            'should' => [
                                [
                                    'multi_match' => [
                                        'query'          => $input['q'],
                                        'fields'         => $fields,
                                        'type'           => 'phrase',
                                        'boost'           => 1.5,
                                    ]
                                ],
                                [
                                    'multi_match' => [
                                        'query'          => $input['q'],
                                        'fields'         => 'title',
                                        'type'           => 'phrase_prefix',
                                        'boost'          => 2.0,
                                        'max_expansions' => 50,
                                        'slop'           => 10
                                    ]
                                ]
                            ]
                        ]
                    ],
                    'field_value_factor' => [
                        'field'    => 'stitcher_list_ranking',
                        'modifier' => 'log1p',
                        'factor'   => 10,
                    ],
                    'boost_mode'         => 'multiply'
                ]
            ],
            'highlight' => [
                'order' => 'score',
                'fields' => [
                    'feed_name'   => [
                        'fragment_size' => 100
                    ],
                    'title'       => [
                        'fragment_size' => 100
                    ],
                    'description' => [
                        'fragment_size' => 100
                    ]
                ]
            ]
        ];

        return Elasticsearch::index($query);

**Comment by cviebrock** [comment]
Sorry for the delay, but I don't think I can help with this.  My package doesn't do any "complaining" of it's own; any errors you get are passed along from the `\Elasticsearch\Client`, so you are most likely missing something in your query and/or configuration.
