### ISSUE TITLE
Integration Demo Sample

### ISSUE THREAD

**Issue by malekbenelouafi** [mailerlite/laravel-elasticsearch#57]
Hi, 
Please I try to make an elasticsearch on my Laravel 5.8 project. 
So first I install elacticseach in my macOs:
**brew install elasticsearch**
After that, I create a new laravel project and I download your package but I didn't figure it out.
Can you please add a sample demo for use, I would be very grateful for that. Thank's.

**Comment by cviebrock** [comment]
Assuming that brew installs ES to run on the standard port 9200 on localhost, then the instructions for configuring the connection are in the README.md.

Creating a sample of creating, populating, and searching an ES index are beyond the scope of this package .. which is really just a convenience wrapper for the official ES client.  The documentation [there](https://github.com/elastic/elasticsearch-php) is probably what you want ... except for the convenience of using my package's facade, etc., to make set up the connection and make queries.
