### ISSUE TITLE
Doesn't read .env config

### ISSUE THREAD

**Issue by thewasta** [mailerlite/laravel-elasticsearch#60]
Just installed cviebrock from packalyst with this:

> composer require cviebrock/laravel-elasticsearch

This is my .env file
> ELASTICSEARCH_HOST=192.168.1.142
ELASTICSEARCH_PORT=9200
ELASTICSEARCH_SCHEME=http
ELASTICSEARCH_USER=
ELASTICSEARCH_PASS=

I don't have user and pass.
Actually I'm learning singleton pattern so I have to extends vendor file to one class and then to other class because my project needs, 

First I would like to know how have I to set setHosts() method, I writed this ['192.168.1.142:9200'] which works well, but is not the .env file supposed to configure that? because if I do not overwrite or use method setHosts(). That's why I used setHosts() method. If i don't do this the project is connected to localhost:9200, and don't want it, also I would like to know how to set a different port.

Thanks you

**Comment by SirNarsh** [comment]
Did you publish the config file ?
```php artisan vendor:publish --provider="Cviebrock\LaravelElasticsearch\ServiceProvider"```
in your project does /config/elasticsearch.php exist? This is the file that translates the .env to the package config...

**Comment by thewasta** [comment]
Yes, I did, and I configured it, but still connecting to localhost. I fixed it using facade. Don't know why it doesn't work well.
Thanks

**Comment by SirNarsh** [comment]
You don't need to modify the '/config/elasticsearch.php' itself since you already changed the .env file, it should stay as it is, can you post your /config/elasticsearch.php.
