### ISSUE TITLE
How do i use this package?

### ISSUE THREAD

**Issue by nachijr4** [mailerlite/laravel-elasticsearch#64]
I want to use this package for my laravel elasticsearch project, but i dont know how to include this package in my project. 
![image](https://user-images.githubusercontent.com/47301844/58244661-b2bc3a00-7d70-11e9-857b-27c7f2c2dca7.png)
This is the error i get when i use it

**Comment by vino-jasuba** [comment]
@nachijr4, have you imported the `Elasticsearch` facade in the controller?

**Comment by cviebrock** [comment]
Did you follow the installation instructions in the README file?  I don't think anything is missing from there...
