### ISSUE TITLE
Filter research

### ISSUE THREAD

**Issue by Bybeez** [mailerlite/laravel-elasticsearch#66]
Hello, I'm trying to filter results by dates, I tried adding a "filter" parameter in my search query but I got an error saying it was not an authorized parameter. How can I do it ?

**Comment by cviebrock** [comment]
Any error like that isn't going to be related to _this_ package, which is really a Laravel convenience wrapper for the official ES PHP client.

Have you tried asking on https://github.com/elastic/elasticsearch-php/issues ?

**Comment by cviebrock** [comment]
Closing due to no response.  Feel free to re-open or comment if you are still having issues.
