### ISSUE TITLE
where to add $return = Elasticsearch::index($data);

### ISSUE THREAD

**Issue by mukeshphpdev** [mailerlite/laravel-elasticsearch#71]
$data = [
    'body' => [
        'testField' => 'abc'
    ],
    'index' => 'my_index',
    'type' => 'my_type',
    'id' => 'my_id',
];

$return = Elasticsearch::index($data);

where to add these code?

**Comment by cviebrock** [comment]
Sorry for the delayed response.  I'm going to assume you figured this out already, so I'm closing the ticket.

I also don't think your question is specific to how to use this package.  The package is a simple wrapper around the main Elastic client, so you would use it pretty much the same way you would use that (except that this package handles all the configuration for you).
