### ISSUE TITLE
Missing Parameter in returned response from the AWS Handler

### ISSUE THREAD

**Issue by HalimNaim** [mailerlite/laravel-elasticsearch#73]
I've Version 4.1.1 of this package with version 7.5 for elasticsearch. 

On [this line in the Factory](https://github.com/cviebrock/laravel-elasticsearch/blob/master/src/Factory.php#L135) a response is returned from the AWS handler. It is missing a property named `primary_port` in `transfer_stats` that is required by the elasticsearch library [here](https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Connections/Connection.php#L379)

Factory.php
```
 // Convert the PSR-7 response to a RingPHP response
 return new \GuzzleHttp\Ring\Future\CompletedFutureArray([
        'status' => $response->getStatusCode(),
        'headers' => $response->getHeaders(),
        'body' => $response->getBody()->detach(),
        'transfer_stats' => ['total_time' => 0],
        'effective_url' => (string)$psr7Request->getUri(),
]);
```

Connection.php
```
 public function logRequestSuccess(array $request, array $response): void
    {
        $this->log->debug('Request Body', array($request['body']));
        $this->log->info(
            'Request Success:',
            array(
                'method'    => $request['http_method'],
                'uri'       => $response['effective_url'],
                'port'      => $response['transfer_stats']['primary_port'],
                'headers'   => $request['headers'],
                'HTTP code' => $response['status'],
                'duration'  => $response['transfer_stats']['total_time'],
            )
        );
        $this->log->debug('Response', array($response['body']));
```
Added in [this commit](https://github.com/elastic/elasticsearch-php/commit/98c336baf3f1310d73c2ec93454d05c618ec25ae#diff-1b0215334399d80759820e3229367adf)
On 2019-09-19

**Comment by cviebrock** [comment]
I didn't write the AWS portion of this package, so I'm a bit unclear as to what's needed.  Should I be changing the Factory to do something like:

```
                    return new \GuzzleHttp\Ring\Future\CompletedFutureArray([
                        'status'         => $response->getStatusCode(),
                        'headers'        => $response->getHeaders(),
                        'body'           => $response->getBody()
                                                     ->detach(),
                        'transfer_stats' => [
                            'total_time' => 0,
                            'primary_port' => '',
                        ],
                        'effective_url'  => (string)$psr7Request->getUri(),
                    ]);
```

I'm not sure what that value should be.  Could you make a PR to fix this?

**Comment by HalimNaim** [comment]
Yeah sure, I would love to.

**Comment by HalimNaim** [comment]
Hey, they have fixed it on their side 6 days ago. [Here](https://github.com/elastic/elasticsearch-php/issues/925)

The port is the port used to connect to ES. For the AWS case I think it can be inferred from the scheme used. http or https. 

I can still write the PR if you would like to add it.

**Comment by cviebrock** [comment]
If you think it's necessary now, then a PR would be great.  Thanks!

**Comment by cviebrock** [comment]
Closing due to no response.  Feel free to re-open or comment if you are still having issues.
