### ISSUE TITLE
Elasticsearch-PHP requires cURL, or a custom HTTP handler

### ISSUE THREAD

**Issue by evanzme** [mailerlite/laravel-elasticsearch#74]
```
Elasticsearch-PHP requires cURL, or a custom HTTP handler. {"exception":"[object] (RuntimeException(code: 0): Elasticsearch-PHP requires cURL, or a custom HTTP handler. at /vendor/elasticsearch/elasticsearch/src/Elasticsearch/ClientBuilder.php:184)
```
it's a error in production env recently,before it's ok.

**Comment by cviebrock** [comment]
This seems like an issue with the underlying [ES PHP library](https://github.com/elastic/elasticsearch-php).

Actually ... do you have the curl module enabled on your PHP build (command line check: ` php -m | grep curl`)?

**Comment by evanzme** [comment]
> This seems like an issue with the underlying [ES PHP library](https://github.com/elastic/elasticsearch-php).
> 
> Actually ... do you have the curl module enabled on your PHP build (command line check: ` php -m | grep curl`)?

now, it's ok. thank you.
