### ISSUE TITLE
Doesn't work for Laravel 7.x or missing instructions?

### ISSUE THREAD

**Issue by icc** [mailerlite/laravel-elasticsearch#82]
Following the readme, I'm stuck at the following part:
> You can now replace those last two lines with simply:
>```php
>$return = Elasticsearch::index($data);
>```
It would appear not, as this simply throws an `Class 'App\\Http\\Controllers\\Elasticsearch' not found` error. Is something special required to load this facade in Laravel 7? 

I tried including the following as well, but that did not help:
```php
use Cviebrock\LaravelElasticsearch\Facade as Elasticsearch;
```

Note: Using the ES Client directly works fine.

**Comment by kmielke** [comment]
i also added the following line to config/app.php
`        /*
         * Package Service Providers...
         */
        Cviebrock\LaravelElasticsearch\ServiceProvider::class,
`

then in the controller
`use Cviebrock\LaravelElasticsearch\Facade as Elasticsearch;`

After that the following was working for me.

```
    /**
     * Display a listing of the resource.
     *
     * @return JsonResponse
     */
    public function show()
    {
        //
        return response()->json(Elasticsearch::info());
    }
```

**Comment by cviebrock** [comment]
@icc It sounds like the service provider isn't auto-registering (which is why @kmielke 's suggestion to update `config/app.php` would work).

Which version of Laravel are you on?

**Comment by kmielke** [comment]
composer info shows laravel/framework v7.4.0

**Comment by icc** [comment]
Thank you for all the suggestion. I finally got it working by simply adding
```php
use Elasticsearch;
```
at the top of the file. 
I guess I was overthinking and didn't realize it was in the top namespace. Probably my bad, but it would be nice if this was mentioned under **Usage** as it's not very common to be coding without a namespace in Laravel.
