### ISSUE TITLE
Consider using fully qualified class names in doc blocks to avoid issue with laravel-ide-helper

### ISSUE THREAD

**Issue by SeinopSys** [mailerlite/laravel-elasticsearch#88]
There is a long-standing issue with laravel-ide-helper, specifically barryvdh/laravel-ide-helper#627 which causes the resolved class for doc blocks to be incorrect if imported via `use`. While this is in no way a fault of your library I would like to ask you to consider switching to fully qualified class names in this library's doc blocks.

I had a quick look through the `src` folder and from what I could see the only line affected is here, everywhere else `Client` appears to be a fully qualified reference.

https://github.com/cviebrock/laravel-elasticsearch/blob/c0216e3f201d48482046413778b5befe0970632c/src/Manager.php#L52

**Comment by Observer5** [comment]
![image](https://user-images.githubusercontent.com/45023046/90090727-5c615f80-dd57-11ea-9cc7-52fefe0e9800.png)
no autocomplete is terrible

**Comment by cviebrock** [comment]
Fixed in 4.2.2 and 8.0.0.  Let me know if that solves things for you!

**Comment by SeinopSys** [comment]
Working well with version 4.2.2, not sure what 8.0.0 is, but thank you either way!
