### ISSUE TITLE
Class 'Elasticsearch' not found from test classes

### ISSUE THREAD

**Issue by wellbornman** [mailerlite/laravel-elasticsearch#91]
I used "Elasticsearch" with static method "search", (Elasticsearch::search()) in my model and used my model's methods many times in my controller, and everything works fine,
Model\Example.php
```php
use Elasticsearch;
class Example {
     public static function example(){
            $params = ...;
            $result = Elasticsearch::search($params);
            ...
     }
}
```
Controller\ExampleController.php
```php
use Model\Example;
class ExampleController extends Controller {
     public function example(){
            $result = Example::example();
            ...
     }
}
```
but when I use same code I wrote in my controller in my test classes, I encounter this error:
Error: Class 'Elasticsearch' not found,
```php
use Model\Example;
class ExampleTest extends TestCase
{
    public function testBasicTest()
    {
        $response = Example::example();
        ...
    }
}
```
whats is the problem?

**Comment by nsaliu** [comment]
Hi @wellbornman ,
which class are you extending in your test class?

I see `TestCase`, but in which namespace this class are?

**Comment by cviebrock** [comment]
Closing due to no response.  Feel free to re-open or comment if you are still having issues.

**Comment by wellbornman** [comment]
`namespace Tests;

use App\User;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase`

**Comment by wellbornman** [comment]
```
namespace Tests;
use App\User;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase{
.....
}
```

**Comment by nsaliu** [comment]
@wellbornman can you try to extend `Cviebrock\LaravelElasticsearch\Tests\TestCase` in your test class instead `Illuminate\Foundation\Testing\TestCase as BaseTestCase`
